### PR TITLE
Markdown labels

### PR DESCRIPTION
**Pull request by will-moore**
Adds support for markdown in panel labels as requested in https://trello.com/c/BNjiEiAZ/3-labels-italics

screen shot 2017-05-02 at 15 31 20

To test:

- Create figure labels including *italics*, **bold** and ***bold italic*** styles with markdown.
- Check that they render correctly on the figure itself (in various locations on each panel).
- See that the [M] button beside the 'Add Labels' heading shows the Markdown info dialog.
- Check that the figure exports as PDF and TIFF with correctly formatted labels. 
- Also: fixed wrapping of figure labels when label is wider than panel (previously these wrapped in the figure app but not in exported PDF/TIFF). Now they extend up to 1 panel width either side of panel.
NB: Python markdown is not currently installed on eel server, so you will need to enter html labels to see these formatted correctly on export. See http://web-dev-merge.openmicroscopy.org/figure/file/17802/ (user-3).

### CODE REVIEW

**Comment by waxenegger** [comment]
Very nice feature, the help menu is a good idea given the various markdown formats.

The display in figure works for bold, italics and link though the link hidden under the svg (z-index) so that it cannot be clicked in figure itself but that may be intentional.

The no-wrap of longer labels is consistent in figure and exported versions.

I read your remark about python markdown on eel but couldn't see the html tag effects in the pdf/tiff I exported but then again it might be better to wait till eel has the respective markdown library installed anyhow.

**Comment by will-moore** [comment]
@waxenegger Sorry, I forgot that I need to upload the script manually. I just uploaded it now (seems to be working) but can do it again whenever you're ready to test.

**Comment by waxenegger** [comment]
The export works now using html tags.

**Comment by will-moore** [comment]
Bug with non-square panels causing incorrect positioning of left-vertical label (from @bramalingam)

screen shot 2017-05-05 at 14 25 49

**Comment by jburel** [comment]
@bramalingam @will-moore  did you import such images on eel to make the testing easier?

**Comment by bramalingam** [comment]
The markdown suggestions work as expected. Looks good to merge.

**Comment by will-moore** [comment]
@jburel You can use this figure for testing http://web-dev-merge.openmicroscopy.org/figure/file/19809/ (user-1)

**Pull request merged**
