### PR TITLE
flake8 fix

### PR DESCRIPTION
**Pull request by will-moore**
This is failing travis on a bunch of PRs (or has been patched to the PRs).
Would be nice to get this in ASAP.

### CODE REVIEW

**Comment by joshmoore** [comment]
```
E       ModuleNotFoundError: No module named 'numpy'
```
which I assume is in another PR, no?

**Comment by will-moore** [comment]
Grrr, yes @joshmoore that was your commit I just cherry-picked...

**Comment by will-moore** [comment]
Yey - green.
Good to merge?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#143](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/143/). See the [console output](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/143/consoleText) for more details.
Possible conflicts:
  - PR #351 will-moore 'Handle unicode figure names in export'
    - .omeroci/app-srv
  - PR #354 will-moore 'script py3 fixes'
    - .omeroci/app-srv

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#114](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-plugins-push/114/). See the [console output](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-plugins-push/114/consoleText) for more details.
Possible conflicts:
  - PR #351 will-moore 'Handle unicode figure names in export'
    - setup.py
  - PR #354 will-moore 'script py3 fixes'
    - setup.py

--conflicts

**Comment by jburel** [comment]
you have the same commits in multiple PRs...
Need to check the sequence here

**Comment by jburel** [comment]
This PR is the "cleanest" since it fixes the travis issue.
Merging, @will-moore will cherry-pick commits on other PR and clean them

**Pull request merged**
