### PR TITLE
Fix demo build

### PR DESCRIPTION
**Pull request by will-moore**
Updates the ```grunt demo``` task to work with the new build layout.

To test:
 - setup dev environment if not already done ```npm install```
 - ```grunt demo```
 - ```cd demo```
 - ```python -m SimpleHTTPServer```
 - Go to http://localhost:8000/ should load with no errors
 - Open file -> list of figures displayed
 - Pick a file -> should load correctly

cc @carandraug

### CODE REVIEW

**Comment by joshmoore** [comment]
Any idea why things weren't red without this fix?

**Comment by will-moore** [comment]
The demo task is not run by travis.
Even if it was, the task was running OK before now (not failing) but the demo app wasn't working in the browser.

**Comment by will-moore** [comment]
I can at least add the demo task to the current Travis script.

**Comment by will-moore** [comment]
Added ```grunt demo``` to the travis.yml which checks that all the key files of the task were created.

**Comment by carandraug** [comment]
I have tested the changes and the demo target works fine for me too. This is very nice for development. Thank you.

**Comment by jburel** [comment]
* The color of the channel is not picked as track color of the slider used to set the window interval
* The slider's knob do not match what is currently deployed on web-dev-merge i.e. round corner vs sharp corne

**Comment by will-moore** [comment]
@jburel @carandraug The issue with the UI differences in the demo build was because of different versions of jQuery.js, jQuery-UI & jQuery.ui.css used in the demo build.
Looks better now.

**Comment by jburel** [comment]
The layout of the components in preview is different i.e. channel at the top vs channel next to slider
In general we need to review the workflow on how to keep both in synch

**Comment by will-moore** [comment]
@jburel The layout is different if you don't have https://github.com/ome/omero-figure/pull/219 merged in. With that merged into this PR the demo build looks like:

screen shot 2017-06-20 at 15 59 37

**Pull request merged**
