### PR TITLE
add cyan color to drop down menu for LUT (fix #498)

### LINKED ISSUE #498: Cyan color does not appear in the drop-down menu of channel colors
## Bug report

**Describe the bug**
The cyan color is not available by default in the drop-down menu of the channel's color in the preview pane of OMERO.figure.

**To Reproduce**
1. Import an image in OMERO.figure
2. Select it
3. Click on Preview tab
4. Click on the drop-down next to the channel color
5. Cyan color does not appear by default with other standard colors

**Expected behavior**
Having the Cyan color by default in the drop-down menu

**Screenshots**
image

**Desktop :**
 - OS: OMERO.Webclient
 - OMERO.figure : 5.1.0

### PR DESCRIPTION
**Pull request by Rdornier**
Adding the choice for Cyan color in the display LUT.
Fixing #498 issue

### CODE REVIEW

**Comment by will-moore** [comment]
Looks good!

Screenshot 2023-09-20 at 16 00 07

**Review by will-moore — APPROVED** [review]

**Comment by jburel** [comment]
Should ``more colors`` options also be added to the scale bar color menu for consistency?

**Comment by will-moore** [comment]
@jburel I think it's a bit more work to add the "More Colors..." option to scalebar, as you need to create and handle the color-picker response.
But @Rdornier might want to add the `Cyan` option to scalebar and label colour menus?

**Comment by jburel** [comment]
@will-moore Cyan has already been added and it works
so let's keep it like this

**Comment by will-moore** [comment]
Sorry, yes I missed that (was looking *after* the comment at https://github.com/ome/omero-figure/pull/516#issuecomment-1727959030). So I think this is good to merge then 👍

**Pull request merged**
