### PR TITLE
Enable time index offset

### PR DESCRIPTION
**Pull request by Rdornier**
Should fix the time index offset no displayed mentionned here https://github.com/ome/omero-figure/pull/521#discussion_r1363509408

### CODE REVIEW

**Comment by joshmoore** [comment]
Workflows launched.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#311](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/311/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/311/consoleText) for more details.
Possible conflicts:
  - PR #521 Rdornier 'Z-offset attribute label'
    - src/js/models/panel_model.js
  - Upstream changes
    - src/js/models/panel_model.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#312](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/312/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/312/consoleText) for more details.
Possible conflicts:
  - PR #521 Rdornier 'Z-offset attribute label'
    - src/js/models/panel_model.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#319](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/319/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/319/consoleText) for more details.
Possible conflicts:
  - PR #521 Rdornier 'Z-offset attribute label'
    - src/js/models/panel_model.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#320](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/320/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/320/consoleText) for more details.
Possible conflicts:
  - PR #521 Rdornier 'Z-offset attribute label'
    - src/js/models/panel_model.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#321](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/321/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/321/consoleText) for more details.
Possible conflicts:
  - PR #521 Rdornier 'Z-offset attribute label'
    - src/js/models/panel_model.js

--conflicts

**Comment by will-moore** [comment]
This is working as expected:

Screenshot 2023-12-08 at 12 56 58

**Pull request merged**
