### PR TITLE
app-srv changes from josh

### PR DESCRIPTION
**Pull request by will-moore**
Ported from https://github.com/ome/omero-figure/pull/351/commits/d5cddb0f4e6d3882edd9d70629ca406d86a0cb48

That commit was removed from #351 and wasn't needed to get travis passing, maybe due to other fixes elsewhere.
But perhaps we still want some of these changes?

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#116](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-plugins-push/116/). See the [console output](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-plugins-push/116/consoleText) for more details.
Possible conflicts:
  - PR #343 will-moore 'Scalebar units'
    - .omeroci/app-srv

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#117](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-plugins-push/117/). See the [console output](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-plugins-push/117/consoleText) for more details.
Possible conflicts:
  - PR #343 will-moore 'Scalebar units'
    - .omeroci/app-srv

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#118](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-plugins-push/118/). See the [console output](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-plugins-push/118/consoleText) for more details.
Possible conflicts:
  - PR #343 will-moore 'Scalebar units'
    - .omeroci/app-srv

--conflicts

**Comment by joshmoore** [comment]
@will-moore : are you for getting this in before the conflicting PR? I'd say this is good to go based solely on the travis testing.

**Comment by will-moore** [comment]
Yes please, go ahead and merge.
I don't think I need the conflicting changes from #343 anyway. They were only to try alternatives for  uploading the scripts, but that is failing due to unicode issues regardless.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#119](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-plugins-push/119/). See the [console output](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-plugins-push/119/consoleText) for more details.
Possible conflicts:
  - PR #343 will-moore 'Scalebar units'
    - .omeroci/app-srv

--conflicts

**Pull request merged**
