### PR TITLE
Don't update zoom to undefined on setId

### PR DESCRIPTION
**Pull request by will-moore**
Fixes a bug introduced in #527: On `Edit ID` the panel zoom is updated to `undefined` since the incoming image data has no zoom info so `data.zoom` is always undefined.

This results in rendering errors - e.g. Zoom slider `0` and other `NaN` values below:

Screenshot 2024-04-08 at 17 49 39

To test:

 - Zoom a panel, then `Edit ID` to replace image with another.
 - The zoom should remain unchanged and after de-selecting and re-selecting the panel (to trigger update of right panels) the zoom controls, viewport x, y, width, height etc should be rendered correctly.

cc @Rdornier

### CODE REVIEW

**Comment by will-moore** [comment]
@jburel - Any idea what's failing in the above job? Seems that `npm` isn't installed.

Same error on #549 (and I assume on all other PRs when they next try to run checks):

```
+ python setup.py sdist
running sdist
npm install
error: command 'npm' failed: No such file or directory
```

Thanks

**Comment by Rdornier** [comment]
I can indeed reproduce the bug. 
I didn't thought about testing this feature when I added this feature.
Thanks for reporting and fixing it.

**Comment by pwalczysko** [comment]
Reproduced on demo (without this PR). See it fixed on merge-ci.

**Review by pwalczysko — APPROVED** [review]

**Comment by will-moore** [comment]
Released in omero-figure 6.2.1

**Pull request merged**
