### PR TITLE
update OMERO version

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
see https://trello.com/c/cyoBblgp/200-renaming-of-web-app#comment-5803f1d6c2f5c7db6f370fc2

### CODE REVIEW

**Comment by jburel** [comment]
I don't think that is right. it will not be limited to 5.2.6+
4.4 can certainly be dropped.

**Comment by aleksandra-tarkowska** [comment]
I am not sure I understand, Figure 2.0+ is compatible with 5.2.6+, otherwise urls are broken. That's being said, older version of OMERO are only supported with 1.x line. Is that not why we rebased https://github.com/openmicroscopy/openmicroscopy/pull/4856?

**Comment by jburel** [comment]
I have, for example, installed figure using pip (see https://github.com/ome/omero-figure/pull/181)  on docker with omero 5.2.4. 

I will rework the readme since i think it is better to have the instruction included in so it is readable on pypi instead of pointing to figure.openmicroscospy.

are you okay to close this PR?

**Comment by aleksandra-tarkowska** [comment]
@jburel and what was the output of:

```
curl -I http://dockerhost/figure
```

?

**Comment by aleksandra-tarkowska** [comment]
I'm getting:

```
Last login: Mon Oct 17 22:09:43 on ttys001
lifesci-53161:~ ola$ curl -I http://10.0.51.137/figure/
HTTP/1.1 404 NOT FOUND
Server: nginx/1.10.1
Date: Mon, 17 Oct 2016 20:31:10 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive

lifesci-53161:~ ola$ curl -I http://10.0.51.137/omero_figure/
HTTP/1.1 302 FOUND
Server: nginx/1.10.1
Date: Mon, 17 Oct 2016 20:31:14 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Vary: Cookie
Location: http://10.0.51.137/webclient/login/?url=%2Fomero_figure%2F

lifesci-53161:~ ola$ 
```

**Comment by jburel** [comment]
similar: but the way I read things is that figure is incompatible with older version. 
It can still be installed.
I think we need to review all the readme (weberror, gallery etc.)

**Comment by jburel** [comment]
Agree that we need to clarify.
I will work on the readme and add commit to https://github.com/ome/omero-figure/pull/181

**Comment by jburel** [comment]
Closing this PR, clarification added to #181

**Pull request closed without merging**
