### PR TITLE
Open images with

### PR DESCRIPTION
**Pull request by will-moore**
This adds "Open with" support to OMERO.figure.

Uses the `webgateway/open_with/` json data, loading scripts as defined in that data to provide urls for selected image(s) if supported by each Open-with plugin, using the same logic as in https://github.com/openmicroscopy/openmicroscopy/pull/4630.

We always provide the 'Open with: Webclient' link (replaces the previous "Show in Webclient" link). By default the regular webclient 'Image viewer' is also available. In this screen-shot I have added @waxenegger's viewer-ng, allowing you to directly open images in that viewer.

To test:
- configure 'Open with' as described in https://github.com/openmicroscopy/openmicroscopy/pull/4630
- Go to OMERO.figure. Select an image - should see 'Open with' links that are enabled for a single image at top of Info panel (see screenshot).
- If you have configured webclient to 'Open with' OMERO.figure `$ bin/omero config append omero.web.open_with '["omero_figure", "new_figure", {"supported_objects":["images"], "target": "_blank", "label": "OMERO.figure"}]'` this should not show up in figure itself. (Doesn't make sense to "Open with OMERO.figure" when you're already in OMERO.figure!

screen shot 2016-10-13 at 10 40 36

NB: this PR is on top of https://github.com/ome/omero-figure/pull/178, which should be merged first.

### CODE REVIEW

**Comment by jburel** [comment]
Closing this PR so we can fix the set up first https://github.com/ome/omero-figure/pull/181

**Comment by waxenegger** [comment]
Tested locally and this time I didn't have any trouble at all. Can open with the other configured open with option viewer-ng.

image

**Comment by jburel** [comment]
@will-moore: could you update the readme?

**Comment by will-moore** [comment]
Last commit https://github.com/ome/omero-figure/pull/179/commits/1414d5f93651beb220d508b6d3d6d336d9c99102 fixes issue reported by @pwalczysko at https://github.com/openmicroscopy/openmicroscopy/pull/4998#issuecomment-267057048

**Comment by will-moore** [comment]
@jburel PR description updated with:
```
$ bin/omero config append omero.web.open_with '["omero_figure", "new_figure", {"supported_objects":["images"], "target": "_blank", "label": "OMERO.figure"}]'
```
if that's what you meant?

**Comment by jburel** [comment]
No. I was more thinking of a description in `` README.rst``

**Comment by waxenegger** [comment]
Works as expected, showing links:

image

**Comment by will-moore** [comment]
This is working with the current ```open_with``` config of
```
["Image viewer", "webindex", {"supported_objects": ["image"], "script_url": "webclient/javascript/ome.openwith_viewer.js"}]
```
from https://github.com/openmicroscopy/openmicroscopy/pull/4630/files
and
```
'["omero_iviewer", "omero_iviewer_index", {"supported_objects":["images"], "script_url": "omero_iviewer/openwith.js", "label": "OMERO.iviewer"}]'
```
from https://github.com/openmicroscopy/management_tools/pull/260/files
so we can see that OMERO.figure is handling both with/without "label".

**Comment by jburel** [comment]
The display of the README on PyPI is not great for the "long" setup commands
see https://pypi.python.org/pypi?:action=display&name=omero-figure&version=2.0.1

**Comment by jburel** [comment]
for example that's what I had to do for iviewer
https://github.com/ome/omero-iviewer/pull/10/commits/36e52f049eac5c2131376c2cabdf044460896975

**Pull request merged**
