### PR TITLE
Introduce dev version

### PR DESCRIPTION
**Pull request by jburel**
Add dev version 
e.g. https://pypi.python.org/pypi/estimators/0.1.0.dev0

cc @sbesson

### CODE REVIEW

**Comment by joshmoore** [comment]
In http://semver.org/ think this would be `2.0.1-dev0`, but see also https://ziade.org/2011/02/15/do-not-upload-dev-releases-at-pypi/

Other options for these SNAPSHOT-like builds of Python resources:
 * PEP-503 (https://pypi.python.org/pypi/pypiserver/, https://pypi.python.org/pypi/devpi-server,  etc)
 * Artifactory
 * Conda

**Comment by jburel** [comment]
I don't think we will push the dev version to pypi. The problem is mainly  with testPypi, used  a staging mechanism to test the full workflow
we have to bump the version each e.g. figure has a higher number (I was testing the build)
so it is "easy" to forget to roll back the version when we are ready

**Comment by joshmoore** [comment]
> I don't think we will ever push the dev version to pypi. 

:+1:

> The problem is mainly with testPypi

Understood, but I think some of the other suggestions could potentially help there. But we'll need time to investigate.

**Comment by jburel** [comment]
@joshmoore: Agree This is just to see an "option in action"

**Pull request closed without merging**
