### PR TITLE
merge gh-pages into master

### PR DESCRIPTION
**Pull request by jburel**
This PR 
* merges gh-pages into master
* redirects figure.o.org to https://www.openmicroscopy.org/omero/figure/
The gh-pages came with its own history. The ``merge`` command was used with ``--allow-unrelated-histories``,

to test locally, run ``docker run -it --rm -p 4000:4000 -v $PWD:/srv/jekyll jekyll/builder:pages jekyll server -w``
* Enter http://0.0.0.0:4000/ in your browser this should redirect you to https://www.openmicroscopy.org/omero/figure/
* Enter http://0.0.0.0:4000/blog/  in your browser this should redirect you to https://www.openmicroscopy.org/omero/figure/
* Enter http://0.0.0.0:4000/videos.html  in your browser this should redirect you to https://www.openmicroscopy.org/omero/figure/

cc @sbesson @will-moore

### CODE REVIEW

**Comment by pwalczysko** [comment]
Tested the workflow in the header of this PR (locally). Works as expected.

**Comment by sbesson** [comment]
This PR is effectively doing several things

- merging `gh-pages` into `master` (assuming one of the end goal is to delete the `gh-pages` branch in favor of `master`)
- adding the `jekyll-redirect-from` plugin to the Jekyll deployment
- using the redirection plugin to redirect various top-level Jekyll pages to www.openmicroscopy.org


Tested locally and the URLs mentioned in the description redirect as expected. A few questions:

- what about the deeper post URLs? For instance http://figure.openmicroscopy.org/2018/10/03/release-4.0.2.html would keep being served as it is but the top-level links would redirect. Is that the intent?
- is figure.openmicroscopy.org/demo/ also remaining served via GitHub or is it getting redirected?
- in terms of the source code, the merging creates a lot of additional files in the top-level directory. 

 ```
sbesson@ls30630:omero-figure ((3e4cf08...)) $ ls -alh
total 512
drwxr-xr-x   44 sbesson  wheel   1.4K 19 Aug 10:20 .
drwxr-xr-x  147 sbesson  wheel   4.6K 17 Aug 09:21 ..
-rw-r--r--    1 sbesson  wheel   416B 19 Aug 10:10 .bumpversion.cfg
-rw-r--r--    1 sbesson  wheel    56B 30 May  2017 .dockerignore
drwxr-xr-x   15 sbesson  wheel   480B 19 Aug 10:18 .git
-rw-r--r--    1 sbesson  wheel   247B 18 Jul  2019 .gitignore
-rw-r--r--    1 sbesson  wheel   327B 30 May  2017 .jshintrc
drwxr-xr-x    4 sbesson  wheel   128B 19 Aug 10:10 .omeroci
-rw-r--r--    1 sbesson  wheel   320B 19 Aug 10:10 .travis.yml
-rw-r--r--    1 sbesson  wheel    12K 19 Aug 10:10 CHANGELOG.md
-rw-r--r--    1 sbesson  wheel    25B 19 Aug 10:18 CNAME
-rw-r--r--    1 sbesson  wheel   273B 30 May  2017 Dockerfile
-rw-r--r--    1 sbesson  wheel   5.8K 18 Jul  2019 Gruntfile.js
-rw-r--r--    1 sbesson  wheel    34K 30 May  2017 LICENSE
-rw-r--r--    1 sbesson  wheel    68B 16 Nov  2017 MANIFEST.in
-rw-r--r--    1 sbesson  wheel   6.8K 19 Aug 10:10 README.rst
-rw-r--r--    1 sbesson  wheel   385B 18 Jul  2019 SUPPORT.md
-rw-r--r--    1 sbesson  wheel   112B 19 Aug 10:18 _config.yml
drwxr-xr-x    4 sbesson  wheel   128B 19 Aug 10:18 _drafts
drwxr-xr-x    4 sbesson  wheel   128B 19 Aug 10:18 _includes
drwxr-xr-x    4 sbesson  wheel   128B 19 Aug 10:18 _layouts
drwxr-xr-x   31 sbesson  wheel   992B 19 Aug 10:18 _posts
drwxr-xr-x   39 sbesson  wheel   1.2K 19 Aug 10:21 _site
drwxr-xr-x    3 sbesson  wheel    96B 19 Aug 10:18 blog
drwxr-xr-x    5 sbesson  wheel   160B 19 Aug 10:18 css
drwxr-xr-x    6 sbesson  wheel   192B 19 Aug 10:18 demo
drwxr-xr-x    3 sbesson  wheel    96B 19 Aug 10:10 docs
drwxr-xr-x   18 sbesson  wheel   576B 19 Aug 10:18 images
-rw-r--r--    1 sbesson  wheel    13K 19 Aug 10:18 index.html
drwxr-xr-x    3 sbesson  wheel    96B 19 Aug 10:18 javascripts
-rw-r--r--    1 sbesson  wheel    14K 16 Nov  2017 licenses.txt
drwxr-xr-x   12 sbesson  wheel   384B 19 Aug 10:10 omero_figure
-rw-r--r--    1 sbesson  wheel    86K 19 Aug 10:10 package-lock.json
-rw-r--r--    1 sbesson  wheel   957B 19 Aug 10:10 package.json
-rw-r--r--    1 sbesson  wheel   321B 19 Aug 10:18 params.json
-rw-r--r--    1 sbesson  wheel    19B 30 May  2017 requirements-server.txt
-rw-r--r--@   1 sbesson  wheel     5B 30 May  2017 requirements.txt
-rw-r--r--    1 sbesson  wheel    40B 30 May  2017 setup.cfg
-rw-r--r--    1 sbesson  wheel   6.0K 19 Aug 10:10 setup.py
drwxr-xr-x    5 sbesson  wheel   160B 30 May  2017 spec
drwxr-xr-x    4 sbesson  wheel   128B 30 May  2017 src
drwxr-xr-x    3 sbesson  wheel    96B 19 Aug 10:18 stylesheets
drwxr-xr-x    3 sbesson  wheel    96B 18 Jul  2019 test
-rw-r--r--    1 sbesson  wheel   1.2K 19 Aug 10:18 videos.html
```

The latter seems to create a lot of clutter for files which are effectively redirecting and largely unmaintained. As GitHub pages has the option of deploying from the `/docs` directory in addition to root, an option would be to start moving the website source under `/docs`?

**Comment by will-moore** [comment]
Great that you're keeping all the `gh-pages` content. I know most of it is not needed by new users but it's nice to preserve that history for those who want more background.

Moving everything under `/docs` to keep the top level clean sounds like a good plan.

Will we *always* keep  http://figure.openmicroscopy.org deployed, to redirect (or not redirect for some deeper posts as Seb asked)? Or will that go away in due course?

Even if we're only left with reading the posts directly (e.g. like https://github.com/jburel/omero-figure/blob/merge-gh/_posts/2014-08-17-dev-jst-templates.markdown) that is not too bad since they mostly seem to render OK, include images etc. (youtube doesn't embed, but the link is still clickable: https://github.com/jburel/omero-figure/blob/merge-gh/_posts/2014-10-07-release-1.0.0.markdown)

**Comment by jburel** [comment]
* For the deeper posts we could redirect to for example https://www.openmicroscopy.org/2018/02/12/figure-3-2-1.html
* I agree that it generates a lot of extra files so moving under docs is a good ideas.
* demo already exists in the master, @will-moore what do you want to do with it?

**Comment by sbesson** [comment]
If we agree to move the Jekyll source files under `/docs`, it might be easier to perform the operation against the `gh-pages` branch first (and add the redirect) and update the deployment directory in a first step, Then `origin/gh-pages` could be merged into `origin/master` and the source branch of the deployment updated. That would also keep the number of concurrent changes more manageable in case something does not work out and we need to roll back changes.

**Comment by jburel** [comment]
I think that will be easier. Closing this PR

**Pull request closed without merging**
