### PR TITLE
Remove unused function arguments and conversion between radians and degrees

### PR DESCRIPTION
**Pull request by carandraug**
While checking how the rotation is done to add a button for horizontal flip, I noticed this unused arguments and extra computations.

### CODE REVIEW

**Comment by jburel** [comment]
Adding the ``include`` flag so it can be part of the daily merge build
--include

**Comment by joshmoore** [comment]
NB: This may well should be considered a breaking change. An alternative would be to replace use of `this.r` with `rotation` within the function method. However, as is always the case with an unused argument, someone with the background should likely evaluate what was really intended.

**Comment by jburel** [comment]
* the conversion changes makes sense
* better to introduce a new function taking 2 arguments and marking the existing ``correct_rotation`` as deprecated.

**Comment by will-moore** [comment]
Since the third argument ```rotation``` wasn't being used, it's not a breaking change to remove that argument. Users could still call it with 3 arguments without an error.
Also, I wouldn't usually consider methods on a View to be an API that could/would be used externally.

**Comment by jburel** [comment]
True that js offers "such flexibility" (not sure it is a good thing!)

**Comment by jburel** [comment]
Thanks

**Pull request merged**
