### PR TITLE
Reverse intensity

### PR DESCRIPTION
**Pull request by will-moore**
This adds support for Reverse intensity to figure - see https://trello.com/c/11hiGrmx/13-reverse-intensity-codomain

We also update the ```luts_10.png``` with the Janelia LUTs. NB: this is still hard-coded since changing that is more work and will mean that OMERO.figure will rely on https://github.com/openmicroscopy/openmicroscopy/pull/5318 (OMERO 5.3.3 at least).
Can do this in a future PR/release.

This also moves the channel-toggle buttons down beside the sliders, to align OMERO.figure with our other clients. This frees up more space for other buttons beside the image, such as 'flip'. cc @carandraug.

Includes a fix for toggling channels bug: https://trello.com/c/yWFPR9MJ/160-bug-toggle-channels

screen shot 2017-06-13 at 15 21 30

To test:
 - Import images into figure, including some with channels that are saved with reverseIntensity.
 - Should appear same in figure (with reverse intensity enabled where appropriate).
 - Sliders should have gradient for plain colour channels (no LUT)
 - LUT and colour gradient should be reversed with reverse intensity
 - If multiple images are selected, channel should be displayed as 'reverse intensity' only if channel is reversed in ALL images.
 - Color-picker dropdown option 'Reverse Intensity' should be checked if all selected images are reversed.
 - Clicking the 'Reverse Intensity' option should turn it on/off.
 - Layout should look OK as below and other channel controls and rotation/z-projection should be unaffected.
 - Export of figure should respect reverse intensity settings.

### CODE REVIEW

**Comment by carandraug** [comment]
I have been trying this to gain space for the flip button, so thank you.

Maybe rename `src/templates/channel_toggle_template.html` to `src/templates/transformations_template.html` since there's no channel toggle left there?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#465](https://ci.openmicroscopy.org/job/FIGURE-merge/465/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/465/consoleText) for more details.
Possible conflicts:
  - PR #213 will-moore 'slider range fix'
    - src/js/views/channel_slider_view.js

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#466](https://ci.openmicroscopy.org/job/FIGURE-merge/466/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/466/consoleText) for more details.
Possible conflicts:
  - PR #213 will-moore 'slider range fix'
    - src/js/views/channel_slider_view.js

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#467](https://ci.openmicroscopy.org/job/FIGURE-merge/467/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/467/consoleText) for more details.
Possible conflicts:
  - PR #213 will-moore 'slider range fix'
    - src/js/views/channel_slider_view.js

**Comment by carandraug** [comment]
There's an issue if the image is on a server that does not support
reversing the colours (the demo site uses images from the JCB which
does not, and the current IDR also does not).  In such cases, the
reverse option still appears ticked, the slider also reverses the
colours, but the image stays the same.  That can be a bit confusing.
Maybe a message could be displayed the same way it does when trying to
pick a LUT?

screenshot from 2017-06-14 15-40-12

Also, most programs call this invert instead of revert.  ImageJ, Icy,
and Imaris, all programs for microscope image analysis only have
'Invert'.  Both GIMP and Photoshop also use 'Invert'.  GraphicsMagick
and ImageMagick use 'negate'.  So maybe rename "Reverse Intensity"
to "Invert"?

For what is worth, the colours on the slider do not show up at all on
Firefox ESR 45.9 which is the latest on Debian stable but not for much
longer (the last ESR was released on March and a new Debian stable is
planned for release this Friday).

screenshot from 2017-06-14 15-36-53

**Comment by jburel** [comment]
cc @waxenegger for name  suggestion. 
If we go for this option we will need to synchronize all the apps and the main web client
So probably for 5.4 then do all the apps

FYI @carandraug: omero does not run on debian 9 https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=8295

**Comment by jburel** [comment]
Suggested name adjustment added to https://trello.com/c/AN7eXyM3/19-rename-in-viewer-reverse-intensity

**Comment by jburel** [comment]
It is not really obvious that we need to click on "Reverse Intensity" so it can take effect 
It does appear as a button or checkbox but more like text

**Comment by jburel** [comment]
The option is now tagging into account in the script

**Comment by will-moore** [comment]
With the last commit, the options look like this:

screen shot 2017-06-23 at 10 15 37

**Comment by jburel** [comment]
That's better is the checkbox

**Pull request merged**
