### PR TITLE
remove_create_original_file_from_file_obj

### PR DESCRIPTION
**Pull request by will-moore**
This removes the local Figure method ```create_original_file_from_file_obj()``` and uses the Blitz Gateway
copy of the same method.

To test, check that saving a figure works OK.

### CODE REVIEW

**Comment by waxenegger** [comment]
Opened image, added shape and label to then store it. After closing figure and opening the stored file everything I added was there. Working as expected.

**Comment by joshmoore** [comment]
Does this place any version restrictions on figure that weren't already in place?

**Comment by will-moore** [comment]
@joshmoore No, we already require OMERO 5.3.0 and that has this method: https://github.com/openmicroscopy/openmicroscopy/blob/v5.3.0/components/tools/OmeroPy/src/omero/gateway/__init__.py#L3798

**Comment by joshmoore** [comment]
Cheers.

**Comment by jburel** [comment]
excluding this PR to check the travis changes 
to be on the safe side

--exclude

**Comment by jburel** [comment]
removed exclude comment

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#604](https://ci.openmicroscopy.org/job/FIGURE-merge/604/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/604/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - omero_figure/views.py

--conflicts

**Pull request merged**
