### PR TITLE
Inset feature

### LINKED ISSUE #319: New workflow: inset handling
e.g. https://omero.lifesci.dundee.ac.uk/figure/file/364219

 * User adds a potentially ephemeral ROI to an image
 * Likely from the ROI edit dialog (since ROIs aren't clickable in the main UI) or potentially from the "Add labels" dialog, user chooses "Use as inset"
 * A new Image is created (optionally beside or below) cropped to the view window
 * Movement of the ROI updates the cropped view
 * Additionally, an option to "Draw connecting lines" is available to connect one appropriate top and bottom corner from the inset ROI to the cropped image

cc: @pwalczysko @jburel

### PR DESCRIPTION
**Pull request by will-moore**
Fixes #319 

This replaces the tricky "create Inset" workflow (copy Rectangle and paste as Crop region or vice versa) with a single button click, and the Inset panel and Rectangle should stay in sync when either are updated.

To test:

- Select one or more panels and in the right-tab, under `ROIs`, click the "Create Inset" button
- This will create a new Inset Panel and a corresponding Rectangle:

Screenshot 2024-04-26 at 11 06 04

- When you Pan, Zoom, rotate or Resize the Inset Panel, the Rectangle will update in sync (NB: we previously handled rotation when copying crop region and pasting as ROI by creating a Polygon instead of rotated Rectangle)
- When you edit the Rectangle (via the ROI dialog) the Inset Panel will update accordingly
- If you copy and paste the Inset panel to create e.g. split-view panels, each of these panels is "linked" to the original Rectangle (updating any one of them will update the Rectangle and vice-versa)
- If you copy and paste the parent panel that contains the Rectangle, both Rectangles in these panels are linked to the Inset Panel(s)
- Save the Figure, then re-open (can simply refresh the page) and check that the Rectangle and Inset panels are still kept in sync.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#44](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/44/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/44/consoleText) for more details.
Possible conflicts:
  - PR #477 will-moore 'Vite'
    - src/js/views/right_panel_view.js

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#46](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/46/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/46/consoleText) for more details.
Possible conflicts:
  - PR #477 will-moore 'Vite'
    - src/js/views/right_panel_view.js

--conflicts

**Comment by pwalczysko** [comment]
Tested on https://merge-ci.openmicroscopy.org/web/figure/file/5875/ - lgtm actually. The only (slight) question is the copying of the zoomed in viewports -> might be a bit confusing that all the "daughter" viewports are linked to the parent viewport and only the panning is going to make a change and sync -> but I do not have any better suggestion, and indeed, this is in line with the iviewer behaviour and also behaviour in figure itself (selection does not cause change, but change inside selection does)

**Review by pwalczysko — APPROVED** [review]

**Comment by will-moore** [comment]
Thinking about discussion at #578, using a panel border to indicate which inset panel is from which rectangle. cc @Rdornier 

I'm not sure whether this is really needed since most real figures only have 1 or two insets and even with 2 or 3 insets it's usually clear where each has come from.

A panel border could help, but again, in most real figures the inset panels don't have borders, so I wouldn't really want to add one by default to inset panels.
One possibility is that we *ONLY* show a temporary (dashed?) border when the parent panel is selected:
E.g. this is how the figure would look normally:


Screenshot 2024-08-09 at 15 47 38

And when you select the parent panel, you see e.g.
Screenshot 2024-08-09 at 16 04 55

NB: any panel border needs a bit of work to avoid shifting the panel (right and down) and changing the size of the internal viewport area.

I'm not convinced that this is really needed / worth the effort.

However, I think we do need to make it easier to pick the colour for the newly created Inset rectangles: currently they are created with the current ROI colour for that panel, but if there are no ROIs on the panel then you can't change this colour, and if there ARE other ROIs on the panel, changing the colour will also change the ROIs colour.

**Comment by Rdornier** [comment]
Hello, 

> A panel border could help, but again, in most real figures the inset panels don't have borders, so I wouldn't really want to add one by default to inset panels.

Ok, that's fair enough. We can forget about having a default panel color border there. It's better to make it a separate feature.

> I'm not sure whether this is really needed since most real figures only have 1 or two insets and even with 2 or 3 insets it's usually clear where each has come from.

For me, having the possibility to identify the inset remains important. Panel color border wasn't maybe the good idea but maybe labeling insets would probably make more sense (i.e. A/B/C or 1/2/3). This would imply to also add a label to the corresponding ROI but I think this feature is not yet implemented (see #457).

> However, I think we do need to make it easier to pick the colour for the newly created Inset rectangles

Ok

**Comment by will-moore** [comment]
Updated form to allow you to choose position of Inset, as well as colour and line-width for the ROI:

Screenshot 2024-08-23 at 11 36 10

Anybody want to test?

**Comment by Rdornier** [comment]
Hi @will-moore 

I've tested it and it works pretty well ! It's a super nice improvement and I'm sure users will strongly appreciate.

I noticed a weird behavior of the inset line width drop-down
1. When changing to another linewidth, the menu doesn't always expend horizontally

image

2. Modifying the inset line width prevents from modifying it again. I wasn't able to choose `3pt` and then `4pt` ; it fixes the line width to the first selection `3pt`. To reset it, I can either select another image or changing the line width of the ROIs

I don't know if it was intended but I noticed that if you delete an inset, the corresponding ROI is not deleted from the parent image (and vice-versa). Do you plan both parts of the link (inset and ROI) ?

Regarding the big images, if I create an inset on that image, without any zoom, it works correctly but a zoom was already set on the parent image, the inset panel is representing the correct part of the parent image. This is maybe linked to https://github.com/ome/omero-figure/pull/580

image

Last point, which is more a suggestion : it could be great to label both ROI and inset with the same letter/number.

Rémy.

**Comment by pwalczysko** [comment]
@Tom-TBT Do you want to have a look please ?

**Comment by Tom-TBT** [comment]
This PR is amazing. 

I tried to break it, without success:
* with rotation in the source or inset
* moving the ROI in source or inset, before and after rotation
* by cascading insets
* changing the size of the rectangle
* editing the image ids (if changing only one, the inset still works but the images don't match. It's not a bug)

I find the creation of an inset intuitive (for sure easier than before). Also, panning in the inset or changing the rectangle in the ROI edit menu gives the same expected results.

It works really well.


Ah! Finally, I found a bug: when creating the inset from a rotated image, both the inset and the ROI have a rotation (only the new inset should inherit rotation, not the ROI on the source image). Right after panning in the inset, the ROI is updated to what it should be (or the other way around by changing the rectangle in ROI edit, the inset is updated correctly).

image

**Comment by will-moore** [comment]
Thanks @Tom-TBT - good catch! I fixed that now, along with tiny bit of code cleanup.

**Comment by will-moore** [comment]
@Rdornier, @Tom-TBT Can you give a final test of this? Thanks!

**Comment by Rdornier** [comment]
Hi @will-moore 

It works nicely. However, 

> Regarding the big images, if I create an inset on that image, without any zoom, it works correctly but a zoom was already set on the parent image, the inset panel is not representing the correct part of the parent image. This is maybe linked to https://github.com/ome/omero-figure/pull/580

This is not fixed with the more recent code

image


> I don't know if it was intended but I noticed that if you delete an inset, the corresponding ROI is not deleted from the parent image (and vice-versa). Do you plan to delete both parts of the link (inset and ROI) ?

What about this point ?

> Last point, which is more a suggestion : it could be great to label both ROI and inset with the same letter/number.

and this one ?

**Comment by will-moore** [comment]
@Rdornier Thanks for that.
 - I can't seem to reproduce the issue you're seeing there. What's the size of that image? Is it rotated? When you pan the viewport of the inset panel, does the ROI update correctly, or does the mismatch persist? What about if you update the ROI - does the inset panel update correctly?
 - I wasn't sure about delete... I'm kinda thinking that someone *may* want to delete just the ROI or Inset Panel independently of each other. But maybe I'm just being lazy! I'll think about it a bit more...
 - Apologies - I should have responded to that labels suggestion earlier. It is a nice idea, but we still don't support labels on ROIs yet, so I think that's going to be quite a bit more work.

**Comment by will-moore** [comment]
Build failing with...

```
#12 [omero 2/2] RUN dnf install -y -q     git &&     dnf clean all
...
#12 9.488  From       : /etc/pki/rpm-gpg/PGDG-RPM-GPG-KEY-RHEL
#12 10.54 Error: Failed to download metadata for repo 'pgdg16': repomd.xml GPG signature verification error: Bad GPG signature
#12 ERROR: process "/bin/sh -c dnf install -y -q     git &&     dnf clean all" did not complete successfully: exit code: 1
```

**Comment by Tom-TBT** [comment]
On my side everything looks fine, I tried with large images too and neither can I reproduce Remy's issue.
Can you share the image @Rdornier?

**Comment by Rdornier** [comment]
>  I tried with large images too and neither can I reproduce Remy's issue.
 
Ok, that's weird. Maybe it is coming from my side only. I'll check

> Can you share the image

Yes, sure. You can find it on zenodo : https://zenodo.org/records/10629087
It is the `Brightfield H-DAB dataset`

**Comment by pwalczysko** [comment]
> Build failing with...
> 
> ```
> #12 [omero 2/2] RUN dnf install -y -q     git &&     dnf clean all
> ...
> #12 9.488  From       : /etc/pki/rpm-gpg/PGDG-RPM-GPG-KEY-RHEL
> #12 10.54 Error: Failed to download metadata for repo 'pgdg16': repomd.xml GPG signature verification error: Bad GPG signature
> #12 ERROR: process "/bin/sh -c dnf install -y -q     git &&     dnf clean all" did not complete successfully: exit code: 1
> ```

@will-moore  This failure is probably just a blip.  Please see that the tests are [passing on my fork where I have just forked, checked out your branch and pushed to my fork with no changes.](https://github.com/pwalczysko/omero-figure/actions/runs/10726775219). I would suggest you simply rerun the tests (I do not seem to have the perms to do that).

**Comment by jburel** [comment]
> Build failing with...
> 
> ```
> #12 [omero 2/2] RUN dnf install -y -q     git &&     dnf clean all
> ...
> #12 9.488  From       : /etc/pki/rpm-gpg/PGDG-RPM-GPG-KEY-RHEL
> #12 10.54 Error: Failed to download metadata for repo 'pgdg16': repomd.xml GPG signature verification error: Bad GPG signature
> #12 ERROR: process "/bin/sh -c dnf install -y -q     git &&     dnf clean all" did not complete successfully: exit code: 1
> ```

Where did you get that error? local build?

**Comment by will-moore** [comment]
@Rdornier Thanks for the zenodo link.
I tried and I really couldn't see any errors (yet)!

Screenshot 2024-09-06 at 09 58 06

**Comment by Rdornier** [comment]
Thanks for checking !
Hum... Ok, so it seems that the issue is coming from my side.
As I'm working with Docker to develop on omero-figure, I'll have a look to the configs, re-build container... and see if it solves this problem.

**Comment by will-moore** [comment]
@Rdornier - with that last commit, when you delete the Inset Panel, the corresponding ROI will also get deleted.
When you delete the Inset ROI, the Inset Panel *doesn't* get deleted. But that was a fair bit harder to implement and probably not as important?

**Comment by Rdornier** [comment]
> when you delete the Inset Panel, the corresponding ROI will also get deleted.

Perfect, thank you ! I've just tested It and it works as expected.

> When you delete the Inset ROI, the Inset Panel doesn't get deleted. But that was a fair bit harder to implement and probably not as important?

Ok, that's fair. This way is not as important and as obvious as the other one. We can keep it like this.

Regarding the bug on the big image, I re-build my entire docker-compose, which now have the latest image of omero-web, figure..., and I cannot reproduce the error neither. I don't know exactly what was going wrong but, now it works ! 
So, all good from my side.

**Comment by will-moore** [comment]
Thanks for all the testing. Merging...

**Pull request merged**
