### PR TITLE
strokeWidth handling

### PR DESCRIPTION
**Pull request by will-moore**
This extends PR https://github.com/ome/omero-figure/pull/409 (@emilroz), so that the Export script handles `shape.get('strokeWidth')` being a string everywhere.
This PR also fixes the origin of the `strokeWidth` string... 

To test Export Script:
 - See https://merge-ci.openmicroscopy.org/web/figure/file/71026/
 - I created this figure with Line, Rectangle, Ellipse, Arrow and Polygon (and scalebar) all with stroke width of 0.75. 
 - Exported the figure to JSON and edited to replace `:0.75,` with `"0.75",` everywhere.
 - Created a new figure with this JSON - If you `File > Export to JSON` you will see this.
 - To test, exported this to PDF and to TIFF.
 - Compare to check they look the same as the original figure.

To test Paste of crop region:
 - Start a new figure (easier)
 - `Copy` the crop region on one panel (zoomed-in) and `Paste` to create a new Rectangle ROI on a different Panel.
 - File > Export to JSON and search for 'strokeWidth' to check that the value not a string e.g. it should be `"strokeWidth":2` NOT `"strokeWidth":"2"`.

### CODE REVIEW

**Comment by emilroz** [comment]
Looks good @will-moore sorry for missing the comments on https://github.com/ome/omero-figure/pull/409.

**Comment by will-moore** [comment]
That last commit should also fix the cause of the issue: https://github.com/ome/omero-figure/issues/427

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#684](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/684/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/684/consoleText) for more details.
Possible conflicts:
  - PR #410 will-moore 'Crop rotation fixes'
    - src/js/views/right_panel_view.js

--conflicts

**Comment by jburel** [comment]
Created arrow, lines etc.: 
```
[{"type":"Arrow","x1":338.0859090909091,"x2":546.3331818181819,"y1":365.2540909090909,"y2":225.74863636363636,"strokeWidth":1,"strokeColor":"#FFFFFF","id":-47766722043832940},
```

**Comment by jburel** [comment]
I did not have any ``strokeWidth`` when going over the ``crop`` test

**Comment by jburel** [comment]
The ``export script`` test works

**Comment by will-moore** [comment]
@jburel You tested "Paste of crop region" steps OK? Not sure if you saw `"strokeWidth":2`?
Is this good to merge or anything else need addressing?

**Comment by jburel** [comment]
I did not have any "strokeWidth" in json when running the "Crop" test mentioned in the description. The way I read it I should have ``strokeWidth``

**Comment by will-moore** [comment]
@jburel. Did you see the Rectangle created when you pasted the Crop region?
Did the JSON have a Rectangle without any "strokeWidth"?

**Comment by jburel** [comment]
Ok this is time, it works I must have done something incorrectly
```
"strokeWidth":1,"type":"Rectangle"
```

**Comment by jburel** [comment]
merging

**Pull request merged**
