### PR TITLE
Fix Save Figure with no panels

### LINKED ISSUE #336: Bug: findByQuery returns multiple
Somehow it looks like `getObject` has returned multiple objects:

```
2019-07-27 21:45:13,948 INFO [ omero.gateway] (proc.23058) close():1952 closed connection (uuid=27e49e52-6af5-4422-a18c-0931f5b1e6f2)
2019-07-27 21:45:13,949 ERROR [ django.request] (proc.23058) handle_uncaught_exception():256 Internal Server Error: /figure/save_web_figure/
Traceback (most recent call last):
File "/opt/omero/web/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/omero/web/OMERO.web/lib/python/omeroweb/decorators.py", line 486, in wrapped
retval = f(request, *args, **kwargs)
File "/opt/omero/web/venv/lib/python2.7/site-packages/omero_figure/views.py", line 264, in save_web_figure
i = conn.getObject("Image", first_img_id)
File "/opt/omero/web/OMERO.web/lib/python/omero/gateway/__init__.py", line 3236, in getObject
query, params, self.SERVICE_OPTS)
File "/opt/omero/web/OMERO.web/lib/python/omero/gateway/__init__.py", line 4703, in __call__
return self.handle_exception(e, *args, **kwargs)
File "/opt/omero/web/OMERO.web/lib/python/omeroweb/webclient/webclient_gateway.py", line 2110, in handle_exception
e, *args, **kwargs)
File "/opt/omero/web/OMERO.web/lib/python/omero/gateway/__init__.py", line 4700, in __call__
return self.f(*args, **kwargs)
File "/opt/omero/web/OMERO.web/lib/python/omero_api_IQuery_ice.py", line 651, in findByQuery
return _M_omero.api.IQuery._op_findByQuery.invoke(self, ((query, params), _ctx))
ApiUsageException: exception ::omero::ApiUsageException
{
serverStackTrace = ome.conditions.ApiUsageException: Query named:

select obj from Image obj join fetch obj.details.owner as owner join fetch obj.details.creationEvent

has returned more than one Object
findBy methods must return a single value.
Please try findAllBy methods for queries which return Lists.
```

### PR DESCRIPTION
**Pull request by will-moore**
Fixes #336 

To test:
 - Create a new figure (e.g. with a single image)
 - Delete all panels so you have a blank page
 - Save -> Choose a name -> OK
 - Figure should get created. Can see it in File > Open etc.
 - Can Open the file and add images later etc....

### CODE REVIEW

**Comment by joshmoore** [comment]
The change itself looks simple enough; :+1: for merging. 

I'd like to point out though that there's some overlap in the `if`-statements just above and below e.g. a check for `if first_img_id is not None:` on 249. Glancing over more of the code, I then saw an "upload file" duplicated on line 286. Similar to @jburel's recent https://github.com/ome/training-scripts/pull/80, I think we will need to start taking the opportunities of these simple fixes to also reduce overall code complexity. This change doesn't make it _much_ harder to read, but in the sum, someone would need to think a bit longer the next time they come back to this section.

**Comment by pwalczysko** [comment]
OMERO.figure does not seem to work on merge-ci

**Comment by will-moore** [comment]
Figure on merge-ci was temporarily broken by 'Figure CLI' PR. Working now.

**Comment by pwalczysko** [comment]
Works as expected on merge-ci. Ready to merge fmpov

**Pull request merged**
