### PR TITLE
Test test

### PR DESCRIPTION
**Pull request by pwalczysko**
trying to fix the test failures

### CODE REVIEW

**Comment by jburel** [comment]
@pwalczysko is your private branch the same ${{ secrets.OMERO_TEST_INFRA_REF }} i.e. master?

**Comment by pwalczysko** [comment]
> @pwalczysko is your private branch the same ${{ secrets.OMERO_TEST_INFRA_REF }} i.e. master?

Yes, I pushed it to my master, to keep everything the same. I have no idea how to cite a branch. And the changes are taken into account here, I am not seeing probs with flake8 install anymore, but now I can see what you meant with the ``l`` variable and trying to fix it.

**Comment by jburel** [comment]
to site a branch:
ref: NameofYourBranch

**Comment by jburel** [comment]
Another problem you will encounter with your change:
``request.funcargnames`` has been replaced by ``request.fixturenames`` in newer version of pytest

**Comment by pwalczysko** [comment]
I think we have a multiple problems here:

1. I think that we know now how to properly install flake8 - this is via https://github.com/ome/omero-figure/pull/535/commits/a79ee5e6873b6b97efe8feb3b2f9664de30d8e49 
2. But flake8 started to work and reports ``violations`` -> this makes the build fail
3. There are plenty of those violations, 108 according to flake8
4. I also had to rebase this branch on top of master - strangely, the original PR of @will-moore was not in sync with master.
5. As @jburel indicated, the flake8 violations touch the figure code itself, namely mainly the Figure_to_pdf.py script
6. I am trying here something, but the result will almost certainly be me breaking the Figure_to_pdf..py script.

@will-moore : Do you want to cherry-pick https://github.com/ome/omero-figure/pull/535/commits/a79ee5e6873b6b97efe8feb3b2f9664de30d8e49 and try to fix the ensuing errors from there please ?

**Comment by pwalczysko** [comment]
I believe this https://github.com/ome/omero-figure/pull/535#issuecomment-1864814813 will not be possible to achieve in this year yet...

**Comment by pwalczysko** [comment]
Indeed, I am not sure if I am fixing anything - the ``undefined name l`` means clearly I have broken the code... cc @will-moore 

```
flake8.main.application   MainProcess    648 INFO     Found a total of 106 violations and reported 18
./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py:1165:43: F821 undefined name 'l'
./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py:1166:33: F821 undefined name 'l'
./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py:1312:29: F821 undefined name 'l'
./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py:1313:13: F821 undefined name 'l'
./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py:1314:19: F821 undefined name 'l'
./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py:1315:13: F821 undefined name 'l'
./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py:1315:29: F821 undefined name 'l'
./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py:1318:27: F821 undefined name 'l'
./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py:1323:21: F821 undefined name 'l'
./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py:1325:21: F821 undefined name 'l'
./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py:1327:39: F821 undefined name 'l'
./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py:1362:30: F821 undefined name 'l'
./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py:1385:26: F821 undefined name 'l'
./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py:1393:40: E741 ambiguous variable name 'l'
./omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py:2247:13: E741 ambiguous variable name 'l'
./omero_figure/views.py:369:13: E741 ambiguous variable name 'l'
```

**Comment by jburel** [comment]
@pwalczysko @will-moore I have made some progress
The test ``test_export_figure_as`` fails 
@will-moore you may want to have a look https://github.com/jburel/omero-figure/tree/test-test
It uses  my branch https://github.com/jburel/omero-test-infra/tree/update

**Comment by jburel** [comment]
closing
replaced by #537

**Pull request closed without merging**
