### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by jburel**
Add more python code check
and exclude directories generating when prep for pypi upload
Check that travis is green and that figure is still working and the export is working

### CODE REVIEW

**Comment by jburel** [comment]
we have not done any official release of 2.0.x version which is already breaking due to the package re-organisation

**Comment by aleksandra-tarkowska** [comment]
How do you mean? We released 2.0.0 and 2.0.1 to https://pypi.python.org/pypi/omero-figure is that not official?

**Comment by jburel** [comment]
We did not do any public announcement that's what I meant. 
we can bump if necessary

**Comment by will-moore** [comment]
Trying to export a figure I get
```
File "./script", line 652, in build_figure
    if self.exportImages:
AttributeError: 'FigureExport' object has no attribute 'exportImages'
```

**Comment by will-moore** [comment]
Another script error:
```
  File "./script", line 1273, in add_info_page
    line, page_y, style=style_n, thumbSrc=thumb_src)
TypeError: add_para_with_thumb() got an unexpected keyword argument 'thumbSrc'
```

**Comment by jburel** [comment]
@will-moore: the last commits should fix the issue

**Comment by will-moore** [comment]
Found more errors when I tried to export as TIFF with images (missed this before).
```
  File "./script", line 540, in draw_ellipse
    self.pilImg.paste(temp_ellipse, (int(paste_x), int(paste_y)),
AttributeError: 'ShapeToPilExport' object has no attribute 'pilImg'

  File "./script", line 1507, in paste_image
    self.tiffFigure.paste(pil_img, box)
AttributeError: 'TiffExport' object has no attribute 'tiffFigure'

  File "./script", line 1547, in draw_text
    textdraw = ImageDraw.Draw(self.tiffFigure)
AttributeError: 'TiffExport' object has no attribute 'tiffFigure'
```

**Comment by jburel** [comment]
Thanks @will-moore

**Comment by will-moore** [comment]
Just tried with your latest fixes on eel and everything seems to be working fine.
Good to merge.

**Comment by jburel** [comment]
@aleksandra-tarkowska the requested changes have been implemented (still the gh red circle), okay to accept them?

**Comment by jburel** [comment]
Thanks @aleksandra-tarkowska

**Pull request merged**
